const CHANGE_USERNAME = 'CHANGE_USERNAME'
const SET_ID = 'SET_ID'
const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
const GOTO_REGISTER = 'GOTO_REGISTER'
const GOTO_LOGIN = 'GOTO_LOGIN'
const SET_LOGGED_IN = 'SET_LOGGED_IN'
const FAILED_LOGIN = 'FAILED_LOGIN'
const SET_REGISTERED = 'SET_REGISTERED'
const UNAVALIABLE_USERNAME = 'UNAVALIABLE_USERNAME'
const FAILED_REGISTRATION = 'FAILED_REGISTRATION'
const LOAD_GAMES = 'LOAD_GAMES'
const LOAD_USERS = 'LOAD_USERS'

export default {
    CHANGE_USERNAME,
    SET_ID,
    CHANGE_PASSWORD,
    GOTO_REGISTER,
    GOTO_LOGIN,
    SET_LOGGED_IN,
    FAILED_LOGIN,
    SET_REGISTERED,
    UNAVALIABLE_USERNAME,
    FAILED_REGISTRATION,
    LOAD_GAMES,
    LOAD_USERS
}