const MATCHES_UNLOADED = 'MATCHES_UNLOADED'
const LOAD_MATCHES = 'LOAD_MATCHES'
const FULL_LOAD_MATCH = 'FULL_LOAD_MATCH'
const JOIN_MATCH = 'JOIN_MATCH'
const MATCH_NOT_JOINED = 'MATCH_NOT_JOINED'
const INIT_GAME = 'INIT_GAME'
const UPDATE_BOARDSTATE = 'UPDATE_BOARDSTATE'
const FINISH_GAME = 'FINISH_GAME'
const NEXT_PLAYER = 'NEXT_PLAYER'
const SET_MARK = 'SET_MARK'

export default {
    MATCHES_UNLOADED,
    LOAD_MATCHES,
    FULL_LOAD_MATCH,
    JOIN_MATCH,
    MATCH_NOT_JOINED,
    INIT_GAME,
    UPDATE_BOARDSTATE,
    FINISH_GAME,
    NEXT_PLAYER,
    SET_MARK
}