const MATCHES_UNLOADED = 'MATCHES_UNLOADED'
const LOAD_MATCHES = 'LOAD_MATCHES'
const JOIN_MATCH = 'JOIN_MATCH'
const MATCH_NOT_JOINED = 'MATCH_NOT_JOINED'
const INIT_GAME = 'INIT_GAME'

export default {
    MATCHES_UNLOADED,
    LOAD_MATCHES,
    JOIN_MATCH,
    MATCH_NOT_JOINED,
    INIT_GAME,
}